from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.expected_conditions import text_to_be_present_in_element_value

driver = webdriver.Chrome()
driver.maximize_window()
driver.get('https://www.220-volt.ru/')
driver.implicitly_wait(5)
enter = driver.find_element(By.CSS_SELECTOR, 'a>.header-panel-icon>.header-panel-user-icon')
enter.click()
reg = driver.find_element(By.ID, 'reg')
reg.click()
email =driver.find_element(By.CSS_SELECTOR, '.mhbspace-10.box-relative>span>#user_email')
email.send_keys('hd22%^&*!u@mi.ru')
password = driver.find_element(By.CSS_SELECTOR,'.box-inline.col-8>#password1')
password.send_keys('111111')
password_2 = driver.find_element(By.CSS_SELECTOR, '.mhbspace-10.box-relative>.box-inline.col-8>#password2')
password_2.send_keys('111111')
user_name = driver.find_element(By.CSS_SELECTOR, '.mhbspace-10.box-relative>.box-inline.col-8>#user_fullname')
user_name.send_keys('Иванов Алексей Петрович')
user_phone = driver.find_element(By.CSS_SELECTOR, '.mhbspace-10.box-relative>span>#user_phone')
user_phone.send_keys('89999999999')
text_to_be_present_in_element_value('.mhbspace-10.box-relative>span>#user_email', 'Неправильный email адрес')
text_to_be_present_in_element_value('.box-inline.col-8>#password1', 'Пароль должен содержать от 8 до 32 символов')
text_to_be_present_in_element_value('.mhbspace-10.box-relative>.box-inline.col-8>#password2', 'Пароль должен содержать от 8 до 32 символов')
driver.quit()